"""Deterministic language and origin rules (see docs/analyzer/python-v1.md).

Origin is decided per file by the first matching rule, in this order:

1. ``origin.vendor_directory``  a path directory named ``vendor``, ``vendored`` or ``third_party``
2. ``origin.build_directory``   a path directory named ``build``, ``dist`` or ``*.egg-info``
                                that is not itself a Python package (no ``__init__.py``)
3. ``origin.generated_header``  a comment in the first 10 lines containing a generated marker
4. ``origin.docs_extension``    a documentation extension (``.md``, ``.markdown``,
                                ``.rst``, ``.adoc``)
5. ``origin.default_source``    anything else

Directories get an origin only when they are themselves a vendor or build marker.
"""

from __future__ import annotations

import re
from collections.abc import Callable, Sequence

from xraymyrepo.cim import Origin

from .facts import OriginFact, Span

LANGUAGES_BY_EXTENSION: dict[str, str] = {
    ".py": "python",
    ".pyi": "python",
    ".toml": "toml",
    ".json": "json",
    ".md": "markdown",
    ".markdown": "markdown",
    ".rst": "restructuredtext",
    ".adoc": "asciidoc",
    ".sh": "shell",
    ".bash": "shell",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".mts": "typescript",
    ".cts": "typescript",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".html": "html",
    ".css": "css",
}

VENDOR_DIRECTORIES = frozenset({"vendor", "vendored", "third_party"})
BUILD_DIRECTORIES = frozenset({"build", "dist"})
DOCS_EXTENSIONS = (".md", ".markdown", ".rst", ".adoc")
GENERATED_MARKERS = ("@generated", "auto-generated", "autogenerated", "do not edit", "generated by")
GENERATED_HEADER_LINES = 10
_COMMENT_PREFIXES: dict[str, tuple[str, ...]] = {
    "python": ("#",),
    "shell": ("#",),
    "toml": ("#",),
    "yaml": ("#",),
    "typescript": ("//", "/*"),
    "javascript": ("//", "/*"),
}
_DEFAULT_SOURCE_PATTERN = "no generated, vendored, docs or build marker"
_LINE_BREAK = re.compile(r"\r\n|\r|\n")


def language_of(name: str) -> str | None:
    dot = name.rfind(".")
    return LANGUAGES_BY_EXTENSION.get(name[dot:].lower()) if dot > 0 else None


def directory_marker(
    parts: Sequence[str], is_python_package: Callable[[int], bool]
) -> tuple[Origin, int] | None:
    """The vendor/build marker among path directories ``parts``: (origin, index).

    ``is_python_package(i)`` says whether directory ``parts[: i + 1]`` contains an
    ``__init__.py`` (such a ``build`` directory is source code, not a build output).
    """
    for i, part in enumerate(parts):
        if part in VENDOR_DIRECTORIES:
            return Origin.VENDORED, i
    for i, part in enumerate(parts):
        if (part in BUILD_DIRECTORIES or part.endswith(".egg-info")) and not is_python_package(i):
            return Origin.BUILD_ARTIFACT, i
    return None


def marker_fact(origin: Origin, marker: str, *, inside: bool, matched_value: str) -> OriginFact:
    rule = "origin.vendor_directory" if origin is Origin.VENDORED else "origin.build_directory"
    return OriginFact(
        origin,
        rule,
        pattern=f"{marker}/**" if inside else f"{marker}/",
        matched_value=matched_value,
    )


def file_origin(
    key: str, name: str, language: str | None, data: bytes, marker: OriginFact | None
) -> OriginFact:
    if marker is not None:
        return marker
    header = generated_header(language, data)
    if header is not None:
        return OriginFact(
            Origin.GENERATED, "origin.generated_header", span=header, ast_type="comment"
        )
    lowered = name.lower()
    for extension in DOCS_EXTENSIONS:
        if lowered.endswith(extension):
            return OriginFact(
                Origin.DOCS, "origin.docs_extension", pattern=f"*{extension}", matched_value=name
            )
    return OriginFact(
        Origin.SOURCE, "origin.default_source", pattern=_DEFAULT_SOURCE_PATTERN, matched_value=key
    )


def generated_header(language: str | None, data: bytes) -> Span | None:
    """Span of the first header comment line containing a generated-code marker."""
    prefixes = _COMMENT_PREFIXES.get(language or "")
    if not prefixes:
        return None
    head = data[:16384].decode("utf-8", errors="replace")
    for number, line in enumerate(_LINE_BREAK.split(head)[:GENERATED_HEADER_LINES], start=1):
        stripped = line.lstrip()
        if not stripped.startswith(prefixes):
            continue
        if any(marker in stripped.lower() for marker in GENERATED_MARKERS):
            start = len(line) - len(stripped)
            return Span(number, start, number, len(line.rstrip()))
    return None
