"""Codebase Intelligence Model (CIM) v1 contract.

Canonical documentation: docs/cim/CIM-v1.md. Three tiers, each immutable:

* snapshot facts      ``SnapshotDocument``: nodes, edges, classifications,
                      unresolved references, extraction issues
* derivation          ``Derivation``: lenses, groups, rollups, metrics, findings,
                      inferred layers
* interpretation      ``Annotation``: append-only AI output; never graph facts
"""

from .classification import Classification, applicable_kinds
from .coverage import CoverageDeclaration, ExtractionIssue, UnresolvedReference
from .derivation import (
    Derivation,
    DerivationRun,
    Finding,
    Group,
    GroupEdge,
    GroupMember,
    InferredLayer,
    Lens,
    NodeMetric,
)
from .document import SnapshotDocument, endpoint_scope
from .edges import (
    EDGE_RULES,
    CallsAttributes,
    Edge,
    HandlesAttributes,
    ImportsAttributes,
    InheritsAttributes,
    RequiresAttributes,
    TestsAttributes,
)
from .enums import (
    AnnotationKind,
    Basis,
    CallKind,
    ClassificationFacet,
    Confidence,
    EdgeKind,
    EndpointProtocol,
    ExclusionAction,
    ExtractionStatus,
    FindingSeverity,
    FunctionKind,
    InheritanceMode,
    IssueSeverity,
    LensKind,
    MatchMethod,
    NodeKind,
    Origin,
    ReferenceKind,
    RequirementScope,
    Role,
    SnapshotStatus,
    TypeKind,
    UnresolvedReason,
)
from .evidence import (
    AiEvidence,
    ConfigEvidence,
    ConventionEvidence,
    DerivedEvidence,
    SourceSpan,
    SpanEvidence,
)
from .fingerprint import ParameterShape, SignatureShape, TypeShape, content_hash, signature_hash
from .interpretation import Annotation
from .keys import (
    REPOSITORY_KEY,
    EndpointKey,
    InvalidKeyError,
    Segment,
    endpoint_key,
    external_package_key,
    group_key,
    package_key,
    parse_endpoint_key,
    path_key,
    symbol_key,
    validate_key,
)
from .lineage import NodeLineage
from .nodes import (
    DirectoryAttributes,
    EndpointAttributes,
    ExternalPackageAttributes,
    FileAttributes,
    FunctionAttributes,
    Node,
    PackageAttributes,
    RepositoryAttributes,
    TypeAttributes,
)
from .provenance import Producer, Provenance
from .refs import EdgeRef, NodeRef, SpanRef
from .snapshot import CIM_SCHEMA_VERSION, AnalysisConfig, RepositoryRef, Snapshot, SnapshotIdentity

__all__ = [
    "CIM_SCHEMA_VERSION",
    "EDGE_RULES",
    "REPOSITORY_KEY",
    "AiEvidence",
    "AnalysisConfig",
    "Annotation",
    "AnnotationKind",
    "Basis",
    "CallKind",
    "CallsAttributes",
    "Classification",
    "ClassificationFacet",
    "Confidence",
    "ConfigEvidence",
    "ConventionEvidence",
    "CoverageDeclaration",
    "Derivation",
    "DerivationRun",
    "DerivedEvidence",
    "DirectoryAttributes",
    "Edge",
    "EdgeKind",
    "EdgeRef",
    "EndpointAttributes",
    "EndpointKey",
    "EndpointProtocol",
    "ExclusionAction",
    "ExternalPackageAttributes",
    "ExtractionIssue",
    "ExtractionStatus",
    "FileAttributes",
    "Finding",
    "FindingSeverity",
    "FunctionAttributes",
    "FunctionKind",
    "Group",
    "GroupEdge",
    "GroupMember",
    "HandlesAttributes",
    "ImportsAttributes",
    "InferredLayer",
    "InheritanceMode",
    "InheritsAttributes",
    "InvalidKeyError",
    "IssueSeverity",
    "Lens",
    "LensKind",
    "MatchMethod",
    "Node",
    "NodeKind",
    "NodeLineage",
    "NodeMetric",
    "NodeRef",
    "Origin",
    "PackageAttributes",
    "ParameterShape",
    "Producer",
    "Provenance",
    "ReferenceKind",
    "RepositoryAttributes",
    "RepositoryRef",
    "RequirementScope",
    "RequiresAttributes",
    "Role",
    "Segment",
    "SignatureShape",
    "Snapshot",
    "SnapshotDocument",
    "SnapshotIdentity",
    "SnapshotStatus",
    "SourceSpan",
    "SpanEvidence",
    "SpanRef",
    "TestsAttributes",
    "TypeAttributes",
    "TypeKind",
    "TypeShape",
    "UnresolvedReason",
    "UnresolvedReference",
    "applicable_kinds",
    "content_hash",
    "endpoint_key",
    "endpoint_scope",
    "external_package_key",
    "group_key",
    "package_key",
    "parse_endpoint_key",
    "path_key",
    "signature_hash",
    "symbol_key",
    "validate_key",
]
