"""Stage 1: file discovery, ignore rules, languages, blob ids and origins."""

from __future__ import annotations

import os
import sys
from pathlib import Path

from xraymyrepo.analyzer import DEFAULT_IGNORE_GLOBS, AnalysisOptions
from xraymyrepo.analyzer.inventory import git_blob_sha, scan
from xraymyrepo.analyzer.options import compile_glob
from xraymyrepo.analyzer.origin import language_of
from xraymyrepo.cim import ExtractionStatus, NodeKind, Origin, SnapshotDocument

from .helpers import run, write_repo


def origin_of(doc: SnapshotDocument, key: str) -> tuple[str, str]:
    (c,) = [c for c in doc.classifications_of(key) if c.facet == "origin"]
    rule = c.evidence[0].provenance.rule
    assert rule is not None
    return c.value, rule


def test_discovers_directories_and_python_files(tmp_path: Path) -> None:
    doc = run(tmp_path, {"app/__init__.py": "", "app/core/models.py": "x = 1\n", "setup.cfg": ""})
    files = {n.key for n in doc.nodes if n.kind is NodeKind.FILE}
    dirs = {n.key for n in doc.nodes if n.kind is NodeKind.DIRECTORY}
    assert files == {"app/__init__.py", "app/core/models.py", "setup.cfg"}
    assert dirs == {"app", "app/core"}
    assert doc.node("app/core/models.py").parent_key == "app/core"
    assert doc.node("app").parent_key == "/"
    assert doc.node("/").name == "sample"


def test_ignored_and_cache_directories_are_not_recorded(tmp_path: Path) -> None:
    doc = run(tmp_path, {
        "src/a.py": "", ".git/config": "", ".venv/lib/x.py": "", "web/node_modules/m/i.js": "",
        "src/__pycache__/a.cpython-313.pyc": b"\x00", ".mypy_cache/x.json": "{}",
        "pkg/.pytest_cache/v": "", "pkg/b.py": "",
    })  # fmt: skip
    keys = {n.key for n in doc.nodes}
    assert {"src/a.py", "pkg/b.py", "web"} - keys == {"web"}  # web holds only ignored files
    ignored = (".git", ".venv", "node_modules", "__pycache__", ".mypy_cache", ".pytest_cache")
    assert not any(part in key for key in keys for part in ignored)
    assert doc.config.ignore_globs == DEFAULT_IGNORE_GLOBS


def test_custom_ignore_globs_are_recorded_in_the_config(tmp_path: Path) -> None:
    options = AnalysisOptions(ignore_globs=("**/fixtures/**", "*.log"))
    doc = run(tmp_path, {"a.py": "", "debug.log": "", "t/fixtures/x.py": "", "t/y.py": ""}, options)
    assert {n.key for n in doc.nodes if n.kind is NodeKind.FILE} == {"a.py", "t/y.py"}
    assert doc.config.ignore_globs == ("**/fixtures/**", "*.log")


def test_glob_semantics() -> None:
    pattern = compile_glob("**/node_modules/**")
    assert pattern.fullmatch("node_modules/x.js") and pattern.fullmatch("a/b/node_modules/")
    assert not pattern.fullmatch("my_node_modules/x.js")
    assert compile_glob("*.log").fullmatch("a.log") and not compile_glob("*.log").fullmatch(
        "d/a.log"
    )


def test_empty_directories_are_not_recorded(tmp_path: Path) -> None:
    (tmp_path / "empty" / "deeper").mkdir(parents=True)
    doc = run(tmp_path, {"a.py": ""})
    assert "empty" not in doc.nodes_by_key


def test_languages_by_extension() -> None:
    names = ("a.py", "a.pyi", "pyproject.toml", "x.md", "Makefile", ".env")
    assert [language_of(n) for n in names] == ["python", "python", "toml", "markdown", None, None]


def test_blob_ids_are_git_blob_ids(tmp_path: Path) -> None:
    doc = run(tmp_path, {"empty.py": "", "hello.txt": "hello\n"})
    assert doc.node("empty.py").blob_sha == "e69de29bb2d1d6434b8b29ae775ad8c2e48c5391"
    assert doc.node("hello.txt").blob_sha == "ce013625030ba8dba906f756967f9e9ca394464a"
    assert git_blob_sha(b"hello\n") == "ce013625030ba8dba906f756967f9e9ca394464a"


def test_origins(tmp_path: Path) -> None:
    doc = run(tmp_path, {
        "src/app.py": "class A: ...\n",
        "src/gen_pb2.py": (
            "# -*- coding: utf-8 -*-\n# Generated by protoc. DO NOT EDIT!\nclass M: ...\n"
        ),
        "docs/guide.md": "# Guide\n",
        "third_party/lib/x.py": "class V: ...\n",
        "dist/pkg-1.0.tar.gz": b"\x1f\x8b",
        "build/__init__.py": "",  # a Python package named build is source code
        "build/tool.py": "",
    })  # fmt: skip
    assert origin_of(doc, "src/app.py") == ("source", "origin.default_source")
    assert origin_of(doc, "src/gen_pb2.py") == ("generated", "origin.generated_header")
    assert origin_of(doc, "docs/guide.md") == ("docs", "origin.docs_extension")
    assert origin_of(doc, "third_party/lib/x.py") == ("vendored", "origin.vendor_directory")
    assert origin_of(doc, "third_party") == ("vendored", "origin.vendor_directory")
    assert origin_of(doc, "dist/pkg-1.0.tar.gz") == ("build_artifact", "origin.build_directory")
    assert origin_of(doc, "dist") == ("build_artifact", "origin.build_directory")
    assert origin_of(doc, "build/tool.py") == ("source", "origin.default_source")
    assert doc.classifications_of("src") == ()  # plain directories carry no origin
    assert doc.classifications_of("third_party/lib") == ()


def test_generated_header_evidence_is_the_comment_span(tmp_path: Path) -> None:
    doc = run(tmp_path, {"g.py": "#!/usr/bin/env python\n  # @generated by tool\nx = 1\n"})
    (c,) = doc.classifications_of("g.py")
    span = c.evidence[0]
    assert (span.type, getattr(span, "start_line", None), getattr(span, "start_col", None),
            getattr(span, "end_col", None), getattr(span, "ast_type", None)) == (
        "span", 2, 2, 22, "comment")  # fmt: skip


def test_vendor_wins_over_generated(tmp_path: Path) -> None:
    doc = run(tmp_path, {"vendor/x.py": "# DO NOT EDIT\n"})
    assert origin_of(doc, "vendor/x.py") == ("vendored", "origin.vendor_directory")


def test_excluded_files_are_recorded_but_not_extracted(tmp_path: Path) -> None:
    doc = run(
        tmp_path, {"vendor/lib.py": "class Hidden: ...\nimport missing\n", "README.md": "#\n"}
    )
    for key in ("vendor/lib.py", "README.md"):
        assert doc.node(key).extraction_status is ExtractionStatus.EXCLUDED
    assert "vendor/lib.py#Hidden" not in doc.nodes_by_key
    assert doc.unresolved_references == ()


def test_unsupported_languages_are_files_only(tmp_path: Path) -> None:
    doc = run(tmp_path, {"run.sh": "echo\n", "web/index.ts": "export {}\n", "a.py": ""})
    assert doc.node("run.sh").extraction_status is ExtractionStatus.UNSUPPORTED
    assert doc.node("web/index.ts").extraction_status is ExtractionStatus.UNSUPPORTED
    assert doc.node("a.py").extraction_status is ExtractionStatus.FULL


def test_symlinks_are_not_followed(tmp_path: Path) -> None:
    write_repo(tmp_path, {"real/a.py": ""})
    _link_directory(tmp_path / "real", tmp_path / "link")
    inventory = scan(tmp_path, AnalysisOptions())
    assert [f.key for f in inventory.files] == ["real/a.py"]
    assert [i.code for i in inventory.issues] == ["symlink_skipped"]


def _link_directory(target: Path, link: Path) -> None:
    """A directory link: a symlink, or a junction where symlinks need privileges."""
    try:
        os.symlink(target, link, target_is_directory=True)
    except OSError:
        if sys.platform != "win32":
            raise
        import _winapi

        _winapi.CreateJunction(str(target), str(link))


def test_inventory_order_is_deterministic(tmp_path: Path) -> None:
    write_repo(tmp_path, {"b/z.py": "", "a.py": "", "b/a.py": "", "B.py": ""})
    first = scan(tmp_path, AnalysisOptions())
    assert [f.key for f in first.files] == [f.key for f in scan(tmp_path, AnalysisOptions()).files]
    assert {f.origin.origin for f in first.files} == {Origin.SOURCE}
